load("@rules_cc//cc:defs.bzl", "cc_library")
cc_library(
    name = "cacLibInclude",
    hdrs = ["cacConst.h", "cacTypeDef.h", "external.h", "stateIdDef.h"],
    visibility = ["//visibility:public"],
)
